language: node_js

node_js:
  - 8.16
  - 10

# Build only commits on master and release tags preventing double builds for PRs
# See https://docs.travis-ci.com/user/pull-requests/#double-builds-on-pull-requests
branches:
  only:
    - master
    - /v[0-9]+\.[0-9]+\.[0-9]+(-.*)?$/

cache: npm

script:
  - npm run lint:test
  - npm run test:report
  - npm run test:coveralls

# TODO: Notifications on failure ?

# TODO: add coveralls
# TODO: Add npm publishing on tags
